# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-24 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_auto_20160624_1219'),
        ('history', '0009_auto_20160512_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyentry',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.RunSQL(
            """
            UPDATE history_historyentry SET project_id=US.project_id FROM userstories_userstory as US WHERE US.id=cast(substring(key from 23) as int) AND key LIKE 'userstories.userstory:%';
            UPDATE history_historyentry SET project_id=I.project_id FROM issues_issue as I WHERE I.id=cast(substring(key from 14) as int) AND key LIKE 'issues.issue:%';
            UPDATE history_historyentry SET project_id=T.project_id FROM tasks_task T WHERE T.id=cast(substring(key from 12) as int) AND key LIKE 'tasks.task:%';
            UPDATE history_historyentry SET project_id=M.project_id FROM milestones_milestone M WHERE M.id=cast(substring(key from 22) as int) AND key LIKE 'milestones.milestone:%';
            UPDATE history_historyentry SET project_id=P.id FROM projects_project P WHERE P.id=cast(substring(key from 18) as int) AND key LIKE 'projects.project:%';
            UPDATE history_historyentry SET project_id=W.project_id FROM wiki_wikipage W WHERE W.id=cast(substring(key from 15) as int) AND key LIKE 'wiki.wikipage:%';
            DELETE FROM history_historyentry WHERE project_id IS NULL;
            """
        ),
        migrations.AlterField(
            model_name='historyentry',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
